#!/bin/bash

SUB_PID=$$  
echo "SUB_PID=$SUB_PID"  
trap "kill -kill $SUB_PID" INT TERM 

while [ 1 ]
do
../cgminer-master/cgminer -o stratum+tcp://stratum.f2pool.com:3333 -u lgyj.zero -p x --icarus-options 115200:1:1 --icarus-timing 3.0=100 --text-only

sleep 30
done
